### ISSUE TITLE
Redirects not working

### ISSUE THREAD

**Issue by kierantaylorio** [chr15m/rogule.com#12]
The following URLs do not correctly redirect to https://rogule.com/

- https://www.rogule.com/
- http://www.rogule.com/

![chrome_2023-03-05-1678043756](https://user-images.githubusercontent.com/51326263/222980960-384dfa2b-397f-4415-a827-5ef1319d70f5.png)

Tested on Windows 11 with Chrome & Firefox

**Comment by chr15m** [comment]
@kierantaylorio thanks for the heads-up. :pray: I've put a redirect in place which should hopefully kick in soon.

**Comment by kierantaylorio** [comment]
No worries, I'm happy to help where I can. 

I tested this morning and it's all working fine from my end now.
