### ISSUE TITLE
The rest key seems to fail for some users

### ISSUE THREAD

**Issue by chr15m** [chr15m/rogule.com#14]
> I would like to report that pressing the . key on an apple laptop (M2) doesn't seem to rest or do anything.

More than one user has reported this. Unclear if it's due to stationary monsters or a bug on some platforms.

**Comment by timothymalcham** [comment]
This also happened (consistently) on an Intel Macbook, using Chrome (v110.0.5481.177), if that's helpful info at all

**Comment by chr15m** [comment]
It is helpful, thank you. What values do you get when you press that button at this site? https://keyjs.dev/

**Comment by chr15m** [comment]
Had another report about this from a player. Tried to replicated this on a Mac but couldn't. Might be M1 Mac only, or non-US keyboards.

**Comment by chr15m** [comment]
If I can only get somebody to send me the results from https://keyjs.dev I should be able to put out a fix.

**Comment by chr15m** [comment]
Player Nikola sent me the following results from keyjs.dev. Unfortunately this has the correct keyCode so it appears that is not the probem.

![image](https://user-images.githubusercontent.com/67130/234013401-eae0b7b5-cd4c-4f48-85f0-18d9f33ac0bd.png)

**Comment by nikolaxhristov** [comment]
> Player Nikola sent me the following results from keyjs.dev. Unfortunately this has the correct keyCode so it appears that is not the probem.
> 
> ![image](https://user-images.githubusercontent.com/67130/234013401-eae0b7b5-cd4c-4f48-85f0-18d9f33ac0bd.png)

This now works for me!

**Comment by chr15m** [comment]
@nikolaxhristov do you mean you are no longer seeing the bug?

**Comment by nikolaxhristov** [comment]
> @nikolaxhristov do you mean you are no longer seeing the bug?

Yup.

**Comment by gogurtenjoyer** [comment]
Mac M1 user here, on Arc browser. Same issue, and the on-screen rest button (in the middle of the arrow buttons) doesn't seem to work either.

**Comment by chr15m** [comment]
@gogurtenjoyer if you open a new private window and try again does the bug disappear? If so it's probably #29.

**Comment by gogurtenjoyer** [comment]
Yes it does - works fine in a new private window - thanks!
