### ISSUE TITLE
Player can't wait after having tried to move into a wall

### ISSUE THREAD

**Issue by OscarCunningham** [chr15m/rogule.com#29]
When the player tries to move into a wall, nothing happens. Then if they then try to wait by pressing the '.' key or clicking the wait button, the wait does not occur. Enemies do not move and health does not recharge.

**Comment by chr15m** [comment]
Thanks very much Oscar, I'm hoping you have found the cause of #14! 🙏

**Comment by OscarCunningham** [comment]
Also you can't wait as the first action in a game, but I thought that might be intentional.

**Comment by chr15m** [comment]
It was not. Thanks!
