### ISSUE TITLE
Put moves in the score

### ISSUE THREAD

**Issue by ralight** [chr15m/rogule.com#8]
Hello! I've been introduced to rogule in the past few days, good job, it's very neat.

I discovered that you regain one health for every 100 moves, which is nice, but it's not possible to tell the difference between a game played with the minimal number of moves and one where you spammed the keys after each battle.

Would you consider adding the number of moves taken to the shared score?

**Comment by chr15m** [comment]
Good idea. I'll move that to the top of the list.

**Comment by chr15m** [comment]
It was actually in there in the first version but people didn't get it. :sweat_smile: Will add it back.

**Comment by chr15m** [comment]
Will push a new build with this change shortly.
