### ISSUE TITLE
Shared content (sometimes) has unclickable URL

### ISSUE THREAD

**Issue by popey** [chr15m/rogule.com#9]
At the bottom of the shared score output is the domain for the game (as below). 
```
Rogule 2023-3-3
🧝 5xp ⛩ 1035 👣 
streak: 2
🟩🟩🟩🟩🟩
⚔ 🐀🐗🧛🧟👹
🌰🌰
🍄

rogule.com
```
On some platforms (Telegram) when pasted it gets automatically turned into a URL...
![image](https://user-images.githubusercontent.com/1841272/222597784-a7b6103b-6822-47fc-a04a-660e124a1eb3.png)

In some cases, the link isn't clickable...
![image](https://user-images.githubusercontent.com/1841272/222598081-27d0fe05-b276-40bb-91c1-4cea771c9cf8.png)

Would it perhaps help to have the protocol `https://` added to the front of the URL to coerce platforms to know it really honestly is a URL?

**Comment by chr15m** [comment]
Thanks @popey I've fixed this now.
